{
  "project_id": "",
  "api": {
    "enabled": true,
    "port": 54321,
    "schemas": ["public"],
    "extra_search_path": ["public", "extensions"],
    "max_rows": 1000
  },
  "db": {
    "port": 54322,
    "shadow_port": 54320,
    "major_version": 15
  },
  "studio": {
    "enabled": true,
    "port": 54323,
    "api_url": "http://localhost"
  },
  "inbucket": {
    "enabled": true,
    "port": 54324
  },
  "storage": {
    "enabled": true
  },
  "auth": {
    "enabled": true,
    "site_url": "http://localhost:5173",
    "additional_redirect_urls": ["http://localhost:4173"],
    "jwt_expiry": 3600,
    "enable_refresh_token_rotation": true,
    "refresh_token_reuse_interval": 10,
    "enable_signup": true
  },
  "functions": {
    "verify_jwt": true
  },
  "analytics": {
    "enabled": false
  }
}
